outdir: results/CCE_H25k_01BC/

seed: 7
epochs: 50

batch_size: 100
num_workers: 10
use_gpu: True

num_frames: 300

device: cuda

load_weights: False
model_path: 'tmp/'

optimizer: adam
base_lr: 0.001
weight_decay: 0.0001
amsgrad: False

momentum: 0.9
nesterov: True

betas: [0.9, 0.999]

scheduler: keras_decay

test_first: False

input_shape: [ 1, 1, 300, 64 ]
base_channels: 64
n_stages: 4
code_dim: 1024
code_norm: True
norm_s: 10.

negative_k: 25
BC_weight: 0.1

arch: spec_resnet_preact_HBC
